### ISSUE TITLE
Various issues on droplet creation for digital ocean

### ISSUE THREAD

**Issue by awishformore** [docker/machine#2890]
I'm keeping the title a bit vague on purpose, but I'm assuming it has to do with timeouts and the execution of docker machine scripts before the droplet environment (file i/o, network i/o) is completely ready. I've also reported the issues to digital ocean support, who did not have any enlightening suggestions.

```
docker-machine create --driver digitalocean --digitalocean-access-token=<token> --digitalocean-region ams2 --swarm --swarm-master --swarm-discovery=consul://<consul-ip>/swarm test-1
Running pre-create checks...
Creating machine...
(test-1) Creating SSH key...
(test-1) Creating Digital Ocean droplet...
(test-1) Waiting for IP address to be assigned to the Droplet...
Waiting for machine to be running, this may take a few minutes...
Machine is running, waiting for SSH to be available...
Detecting operating system of created instance...
Detecting the provisioner...
Provisioning with ubuntu(systemd)...
Error creating machine: Error running provisioning: Something went wrong running an SSH command!
command : sudo apt-get update
err     : exit status 255
output  : 
```

```
docker-machine create --driver digitalocean --digitalocean-access-token=<token> --digitalocean-region ams3 --digitalocean-private-networking test-discover1
Running pre-create checks...
Creating machine...
(test-discover1) Creating SSH key...
(test-discover1) Creating Digital Ocean droplet...
(test-discover1) Waiting for IP address to be assigned to the Droplet...
Waiting for machine to be running, this may take a few minutes...
Machine is running, waiting for SSH to be available...
Detecting operating system of created instance...
Detecting the provisioner...
Provisioning with ubuntu(systemd)...
Error creating machine: Error running provisioning: Something went wrong running an SSH command!
command : 
if ! grep -xq .*test-discover1 /etc/hosts; then
   if grep -xq 127.0.1.1.* /etc/hosts; then 
      sudo sed -i 's/^127.0.1.1.*/127.0.1.1 test-discover1/g' /etc/hosts; 
   else 
      echo '127.0.1.1 test-discover1' | sudo tee -a /etc/hosts; 
   fi
fi
err : exit status 255
output :
```

```
docker-machine create --driver digitalocean --digitalocean-access-token=<token> --digitalocean-region ams3 --digitalocean-private-networking test-discover1
Running pre-create checks...
Creating machine...
(test-discover1) Creating SSH key...
(test-discover1) Creating Digital Ocean droplet...
(test-discover1) Waiting for IP address to be assigned to the Droplet...
Waiting for machine to be running, this may take a few minutes...
Machine is running, waiting for SSH to be available...
Detecting operating system of created instance...
Detecting the provisioner...
Provisioning with ubuntu(systemd)...
Error creating machine: Error running provisioning: Something went wrong running an SSH command!
command : sudo hostname test-discover1 && echo "test-discover1" | sudo tee /etc/hostname
err : exit status 255
output :
```

```
docker-machine create --driver digitalocean --digitalocean-access-token=<token> --digitalocean-region ams3 --digitalocean-private-networking test-discover1
Running pre-create checks...
Creating machine...
(test-discover1) Creating SSH key...
(test-discover1) Creating Digital Ocean droplet...
(test-discover1) Waiting for IP address to be assigned to the Droplet...
Waiting for machine to be running, this may take a few minutes...
Machine is running, waiting for SSH to be available...
Detecting operating system of created instance...
Detecting the provisioner...
Provisioning with ubuntu(systemd)...
Error creating machine: Error running provisioning: Something went wrong running an SSH command!
command : DEBIAN_FRONTEND=noninteractive sudo -E apt-get install -y curl
err : exit status 100
output : Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
curl
0 upgraded, 1 newly installed, 0 to remove and 47 not upgraded.
Need to get 134 kB of archives.
After this operation, 319 kB of additional disk space will be used.
Err http://mirrors.digitalocean.com/ubuntu/ wily/main curl amd64 7.43.0-1ubuntu2
Temporary failure resolving 'mirrors.digitalocean.com'
E: Failed to fetch http://mirrors.digitalocean.com/ubuntu/pool/main/c/curl/curl_7.43.0-1ubuntu2_amd64.deb Temporary failure resolving 'mirrors.digitalocean.com'

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

Like I said, I think the problem has to do with incomplete environment initialization on the droplet, but maybe it could still be fixed by adding better checks / additional pauses to docker machine.

As a second option, could this be related to an unstable network connection?

**Comment by awishformore** [comment]
I just did some more tests with an increased droplet limit, and the problem seems to be mostly gone. I'm not sure it is related, but I did do the previous tests while creating & destroying droplets near the limit continuously. If it crops up again, I will update the issue, but until then, I would suggest closing it and assuming that the problem is on the side of digital ocean when working near the droplet limit.

**Comment by BrianAdams** [comment]
As another data point,  I'm seeing the exact same behavior from digital ocean using the 1.10 rc1.  I only have 12 out of 25 droplets running... so I suspect something else may be going on.

**Comment by awishformore** [comment]
If anyone has ideas on how to further investigate this, I am willing to put in some time. Currently, I'm no longer able to reproduce this behaviour, but it consistently happened over a few days before.

**Comment by zramsay** [comment]
I've been getting a similar error (but only with swarm):
```
docker-machine create --driver digitalocean --digitalocean-access-token $DOTOK --swarm --swarm-discovery token://$SWARM_TOK swarm-agent-01
Running pre-create checks...
Creating machine...
(swarm-agent-01) Creating SSH key...
(swarm-agent-01) Creating Digital Ocean droplet...
(swarm-agent-01) Waiting for IP address to be assigned to the Droplet...
Waiting for machine to be running, this may take a few minutes...
Machine is running, waiting for SSH to be available...
Detecting operating system of created instance...
Detecting the provisioner...
Error creating machine: Error detecting OS: Error getting SSH command: Something went wrong running an SSH command!
command : cat /etc/os-release
err     : exit status 255
output  : 
```
Relatedly, I get this error a lot (`server.pem` not there). In this case, it happens to be related to the swarming but occurs frequently w/o creating swarm. Very non-deterministic (approx 50% of machines, 50% of the time). Happens both when machines are created from command-line or shelled out in parallel. When !swarm, no error throws on machine creation. Solution is to `regenerate-certs`, which always works (but far from ideal), or wait it out...file will *eventually* show up on host though this can take >15 mins. Occurs on both `0.5.6` and `0.5.3`.
```
docker-machine ls
NAME                  ACTIVE   DRIVER         STATE     URL                          SWARM                   DOCKER    ERRORS
swarm-agent-00        -        digitalocean   Running   tcp://159.203.175.243:2376   swarm-master            v1.9.1    
swarm-agent-01        -        digitalocean   Running   tcp://159.203.118.130:2376   swarm-master            Unknown   Unable to query docker version: Unable to read TLS config: open /home/zach/.docker/machine/machines/swarm-agent-01/server.pem: no such file or directory
swarm-master          -        digitalocean   Running   tcp://45.55.52.69:2376       swarm-master (master)   v1.9.1
```

**Comment by zramsay** [comment]
Have replicated all of @awishformore's errors using `libmachine` under the hood rather than the cli. No longer get the `server.pem` error ... now its `Unable to query docker version: Cannot connect to the docker engine endpoint`

**Comment by jjimjam** [comment]
I'm having a terrible time with this too.   "docker-machine create  --driver digitalocean" works perhaps 20% of the time.   

Sometimes I get.

Provisioning with ubuntu(systemd)...
Error creating machine: Error running provisioning: Something went wrong running an SSH Command!
command : sudo apt-get update
err     : exit status 255
output  :


Other times:

Detecting the provisioner...
Error creating machine: Error detecting OS: Error getting SSH command: Something went wrong running an SSH command!
command : cat /etc/os-release
err     : exit status 255
output  :

Sometimes it works, but takes ages to run.   The last one that worked took 7 minutes to do "apt-get update".   

All of the ssh commands appear to take a long time to run.

It's so bad, I can't use it in my project.

I use with swarm and without.   I don't think there's a difference.

**Comment by jjimjam** [comment]
and this:

Provisioning with ubuntu(systemd)...
Error creating machine: Error running provisioning: Something went wrong running an SSH command!
command : sudo hostname dockereg-dgo && echo "dockereg-dgo" | sudo tee /etc/hostname
err     : exit status 255
output  :

It's now got to stage where it doesn't work for me at all in london region.
It just worked first time on default NYC3 region.

**Comment by awishformore** [comment]
@jjimjam maybe you could use code mark-up to make these messages more easily readable?

Anyway, is there anyone with a bit more experience to point me in the right direction? I would like to investigate this further, but I have no idea where to look (or if it's even related to Docker Machine). I'm in contact with the Digital Ocean support and they are aware of this thread, so maybe they can help as well.

**Comment by awishformore** [comment]
I have just received a reply by the Digital Ocean support that actually contradicts what they said before. Here the response I got:

```[...] This should not have anything to do with your droplet limit increase, in the slightest. Nor, would getting close to your limit affect this. It's more likely just random chance. You could have the next 20 SSH attempts directly after a create go through, then the next 10 fail. If your script is trying to SSH in directly after the droplet switches from "New" to "On", then there are absolutely going to be slight variances where some droplets boot faster than others, depending on the hardware they are provisioned to and the image they are using.

From what you describe, this is expected functionality with our API. When a droplet is marked as "powered on" after it is created, that does not mean that the droplet is actually fully booted up and replying to network requests. It just means that it is powered on. In this case, it looks like the network is still in the process of initializing during the droplet's boot process, but our platform does not have any visibility of that: it just knows the droplet is running, not what it is doing. It's like taking a look at the power light on the front of a desktop. That just tells you there's power, not that you can log in yet.

With that in mind, like [...] suggested, I would recommend adding a short, maybe 30 second sleep between the creation completing and when docker machine tries to log itself in. This generally covers the amount of time most base droplets take to start up and initialize networking, but if you're using a custom one, it may take longer of course.

If you'd like this functionality of our API to be different,  I'd suggest adding this suggestion to our feedback page at http://do.co/uvoice. We use that page to help gauge demand for new features, so adding it, or adding your vote, will help us to prioritize when we can implement this feature.
```

**Comment by awishformore** [comment]
As opposed to what was said before:

*It's possible there may be a timeout issue, but normally we don't see many cases of this as the SSH daemon on the droplet normally isn't started until after the network interface is enabled during the boot process.*

**Comment by awishformore** [comment]
Obviously, the cleanest way to solve this would be to have a proper API that tells you when a droplet is actually usable, rather than giving you less than useful information on it's power state. However, their suggestion to add a suggestion to their feedback page does not really leave me hopeful as to the resolution of this issue on their side.

Still, 30 seconds of added wait for every droplet creation does seem excessive. Maybe we could write a "test battery" of commands that cover all error cases, and which we can use to "poll" for ready state over SSH?

**Comment by awishformore** [comment]
More news from the Digital Ocean team:

*Actually, looking into it further, it looks like Docker Machine's DigitalOcean driver just waits for an IP to be assigned. It's not even waiting for the Droplet to be fully created and change from "new" to "on" status. That'll mean that there's even more of a chance that an SSH would fail, since the droplet hasn't even been fully provisioned yet until the status is set to "on".*

*It looks to me like the fluke here is... how is this even working in the first place? Our creations are fast, but this is very precarious. Seems like the stars need to align perfectly in order for it to work, which is impressive that it even works at all.*

I will start looking into this probably this weekend, and see if I can find a simple command that will let me reliably test for a real ready state through the API.

**Comment by tassels** [comment]
Hi there. I thought I'd step in personally since you're pasting my response anyway. 

During the create process, the driver checks if an IP address is assigned, and that's when it assumes the creation is complete (see here: https://github.com/docker/machine/blob/master/drivers/digitalocean/digitalocean.go#L208).

Instead, it should assume the creation is complete when the state changes from "new" to "active" and the droplet is responding to ping. This will ensure that the droplet's boot process has gone far enough for networking to be initialized.

Please correct me if I'm wrong. I haven't had a lot of time to look into this and my Go is a little rusty (I'm on DO's Platform Support team, and am not an Engineer). I may have some more time to look into this later, or possibly this weekend.

**Comment by zramsay** [comment]
nice. this explains a lot and should solve these issues. thanks :+1:

**Comment by anentropic** [comment]
bit of a downer but hopefully it will be fixed soon now the source of problem has been identified

I'm trying to set up my first swarm. I successfully got the consul droplet and then the swarm master droplet running first time.  Trying to get a second node `oceania-1` into the swarm failed with error as above.

If I do `docker info` it shows `Nodes: 1` (just the swarm master)

If I try again to create the second swarm node I get this error:
```
Host already exists: "oceania-1"
```

How do I clean up so I can try again?

**Comment by anentropic** [comment]
never mind, obviously I go to the DO control panel and destroy the droplet from there

**Comment by nathanleclaire** [comment]
Hi all, thanks for the report(s).

> It looks to me like the fluke here is... how is this even working in the first place? Our creations are fast, but this is very precarious. Seems like the stars need to align perfectly in order for it to work, which is impressive that it even works at all.

If you look a little further in the code, you can see that we _do_ wait for an SSH command to run successfully (`exit 0`) before we attempt to go ahead with running more SSH commands: https://github.com/docker/machine/blob/b6be1b79bcb2bf7ef6f74031ed5da3e72b882b4b/libmachine/libmachine.go#L166 .  Once that runs, it's assumed to be safe to go ahead with provisioning.  My guess is that there's some kind of system which is interfering with SSH (e.g. cloudinit or DO's custom post-boot process if they have one) and causing hiccups after this initial `exit 0` "health check". Maybe we need a longer pause, but I'm hesitant to do anything without more info about what the actual issue is.

It won't be possible to diagnose without more info -- the `exit status 255` errors indicate that SSH is not able to properly establish a connection, but are not explaining why so far.  It could be auth-related (unlikely), or network related (more likely).  What would be really great to see if the result of running such a create with a compiled machine binary that runs `ssh` with verbose logging flags set (`-vvv`), which could be added here: https://github.com/docker/machine/blob/master/libmachine/ssh/client.go#L50.

Please try one of these test binaries and please print the `--debug` output which will include this info:

- Windows - https://www.dropbox.com/s/exx4gzdihsftik7/docker-machine-Windows-x86_64.exe?dl=1
- Linux - https://www.dropbox.com/s/9aby632x5sh8vxf/docker-machine-Linux-x86_64?dl=1
- OSX - https://www.dropbox.com/s/7ub43itgteb2vb0/docker-machine-Darwin-x86_64?dl=0

(there's a chance due to some current inelegance of our SSH output parsing, that they might spew some weird looking warnings / errors, but the log should still be useful to me)

> As a second option, could this be related to an unstable network connection?

Yes, definitely, we try to alleviate this a bit using `ConnectTimeout` and `ConnectionAttempts` but if the network is really bad Machine won't work reliably.  My advice if your network is spotty is to maybe create a jump box and run `docker-machine create` inside of a `tmux` session or equivalent, that way you can safely disconnect and the network will be more reliable from the Machine client's end.

> How do I clean up so I can try again?

`docker-machine rm -f oceania-1`, if I'm understanding your situation correctly.

As for the error like `E: Failed to fetch http://mirrors.digitalocean.com/ubuntu/pool/main/c/curl/curl_7.43.0-1ubuntu2_amd64.deb Temporary failure resolving 'mirrors.digitalocean.com'`, this is just DO's package mirrors failing, there's not much Machine can do to recover in this case, so basically you're stuck removing the failed create and starting over (or, in 0.6.0, trying `docker-machine provision` to re-run provisioning).

FYI, if `create` fails at all, I would not count on being able to use the instance at all (`env` etc. won't work), the cert message is usually a red herring that actually means something bombed out during provisioning (which will be better handled in the future especially as `docker-machine provision` gets more robust).

**Comment by nathanleclaire** [comment]
@anentropic Your local Machine "copy" (configuration) still exists, so you need to remove it in Machineland as well.

**Comment by anentropic** [comment]
@nathanleclaire  ok thanks, yes, fixed that part by `docker-machine rm oceania-1`

**Comment by zramsay** [comment]
thanks for the clarification Nathan. Will report back with debug output/luck with `dm provision`.

**Comment by zramsay** [comment]
Here's a [gist](https://gist.github.com/zramsay/d8f1cdea398a216be02f) with `debug` on for the ssh client (changed manually in vendored code). [Here](https://gist.github.com/zramsay/e6de5ffcbb2aa14b3668) is sample code that leads to that output if `machines = []string{"eris-remote-dm-0", "eris-remote-dm-1", "eris-remote-dm-2"}`. (sample code from [this branch](https://github.com/eris-ltd/eris-cli/tree/remotes) ). My hunch is that there's something funky going on with the filepaths ... although things definitely work *sometimes* which leads me to reject that hypothesis.

**Comment by tassels** [comment]
Unfortunately, I haven't been able to reproduce this behavior from my end this weekend, and as @nathanleclaire stated, since it is waiting for SSH, that shouldn't be the issue.

Could still be some weird interaction with cloudinit, which we're investigating from our end (but haven't been able to reproduce, either).

**Comment by zramsay** [comment]
ok, there's definitely something wrong with my libmachine implementation...though that doesn't explain these errors with porcelain `docker-machine create ...`

**Comment by zramsay** [comment]
can confirm `docker-machine provision` helps, though it can sometimes take 2-3 tries.

**Comment by nathanleclaire** [comment]
@zramsay Hm, I would not count on the plumbing being 100% free of bugs when used directly, there's definitely still some issues and tight coupling to the CLI in some places.

**Comment by jjimjam** [comment]
[failed.txt](https://github.com/docker/machine/files/113819/failed.txt)

Here's a log from running with the test binary and --debug flag. 
Today, it's failing about 75% of the time.  I'm trying to create a small Digital Ocean machine in london.

When if works, the top of the log looks like this:  [succeeded.txt](https://github.com/docker/machine/files/113823/succeeded.txt).     This one gets "Connection established" after several "Connection refused".     The one that fails gets "Connection established" after several "Connection timed out".

I hope this helps.

**Comment by nathanleclaire** [comment]
@jjimjam How's the network where you're working from (to DigitalOcean's datacenter -- in NY by default)?  It looks like Machine is getting a few successful connections where you are but then they are timing out when it goes to follow up, which indicates network conditions are probably not ideal.  If issues persist, I'd recommend either:

1. using a hand-created server as a jump box (and possibly have a `tmux` session), running the Machine commands from there, as outbound network will be much more reliable, or --
2. Creating droplets in a datacenter closer to you. Are you in London, trying to create droplets in London?  In that case I'd be suspicious of your outbound connection speed.

**Comment by jjimjam** [comment]
@nathanleclaire Thanks for your reply.   Yes, it does look like network connection problems.   My internet connection is normally pretty good.   I'll perhaps investigate a bit more.

Yes, I am near London, creating droplets in the London datacenter.    I have tried the NY datacenter twice and it worked both times without error.   I'll try that again and also try the jump box suggestion.

**Comment by zramsay** [comment]
@nathanleclaire Noted. It's works quite nicely so far.

**Comment by kitotik** [comment]
Anecdotally, it's starting to seem like an issue when attempting to create a droplet with a name that has been used previously.

In my testing I have yet to see the error happen when using a new unique name for the droplet.

**Comment by nathanleclaire** [comment]
Yes, historically duplicate names tend to be kind of a headache for several of the drivers.

**Comment by nathanleclaire** [comment]
Since I think this issue is about as tied up as it's going to get (and diverging from the original report a bit), I'm going to close -- however all should feel free to open new issues with more specific symptoms if things continue to look problematic.  Thanks!

**Comment by jjimjam** [comment]
I was wondering the same thing as @kitotik.   I'm repeatedly destroying and recreating a droplet with the same name.    If that's the case then it's a problem at digital ocean, isn't it?

**Comment by dminca** [comment]
:+1: main thing is to pick a server closer to your location. Since I'm form Romania, I've added `--digitalocean-region "FRA1"` and it worked ok.

**Comment by twang2218** [comment]
I got similar issue with Digital Ocean on Ubuntu 16.04 image, I think it might relate to systemd as well, as I got more success in 14.04 image than 16.04. Many times, it's run into conflicts with maybe the default `apt-get update` or `apt-get install` task, as I got following error:

```
...
Get:23 http://security.ubuntu.com/ubuntu xenial-security/multiverse i386 Packages [1,344 B]
Get:24 http://security.ubuntu.com/ubuntu xenial-security/multiverse Translation-en [628 B]
Fetched 9,244 kB in 6s (1,480 kB/s)
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
```

or 

```
...
Get:22 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages [1,176 B]
Get:23 http://security.ubuntu.com/ubuntu xenial-security/multiverse i386 Packages [1,344 B]
Get:24 http://security.ubuntu.com/ubuntu xenial-security/multiverse Translation-en [628 B]
Fetched 9,339 kB in 2s (4,498 kB/s)
Reading package lists...
E: Failed to fetch http://mirrors.digitalocean.com/ubuntu/dists/xenial-updates/universe/source/Sources.xz  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

After I `rm -rf /var/lib/apt/lists/*`, and run the provision again, it will be succeeded. Looks like it will be more likely to success if it can wait a little bit longer.
