### ISSUE TITLE
Error on creating docker-machine with vmware-fusion driver

### ISSUE THREAD

**Issue by dtomasi** [docker/machine#3105]
Hey Guys,

I ran in an Error while trying to create a docker-machine using VMware Fusion Version 8.1.0 (3272237). I used the following versions of docker and docker-machine on OS X El Capitan 10.11.3 (15D21).

```bash
Docker version 1.10.1, build 9e83765
docker-machine version 0.5.3, build 4d39a66
```

```bash
Error creating machine: Error in driver during machine creation: Machine didn't return an IP after 120 seconds, aborting
```

A fresh installation of docker via brew does not help. :-(

I´ve seen some closed issues for previous versions but nothing that is still open ... so sorry if I created a duplicate ...

**Comment by nathanleclaire** [comment]
cc @frapposelli

**Comment by frapposelli** [comment]
@dtomasi can you please re run the creation with `-D` and paste the log?

**Comment by dtomasi** [comment]
@frapposelli here is what my terminal says ... 

```
Dominiks-MBP:~ dominik$ docker-machine -D create --driver vmwarefusion --vmwarefusion-cpu-count 2 --vmwarefusion-disk-size 80000 --vmwarefusion-memory-size 4096 default
Docker Machine Version:  0.6.0, build e27fb87
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver vmwarefusion
Plugin server listening at address 127.0.0.1:53115
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(flag-lookup) Calling .GetMachineName
(flag-lookup) Calling .DriverName
(flag-lookup) Calling .GetCreateFlags
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver vmwarefusion
Plugin server listening at address 127.0.0.1:53119
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(default) Calling .GetMachineName
(default) Calling .DriverName
(default) Calling .GetCreateFlags
(default) Calling .SetConfigFromFlags
Running pre-create checks...
(default) Calling .PreCreateCheck
(default) DBG | local Boot2Docker ISO version:  v1.10.2
(default) Calling .GetConfigRaw
Creating machine...
(default) Calling .Create
(default) DBG | local Boot2Docker ISO version:  v1.10.2
(default) Copying /Users/dominik/.docker/machine/cache/boot2docker.iso to /Users/dominik/.docker/machine/machines/default/boot2docker.iso...
(default) Creating SSH key...
(default) Creating VM...
(default) Creating disk '/Users/dominik/.docker/machine/machines/default/default.vmdk'
(default) Virtual disk creation successful.
(default) Starting default...
(default) DBG | executing: /Applications/VMware Fusion.app/Contents/Library/vmrun start /Users/dominik/.docker/machine/machines/default/default.vmx nogui
(default) Waiting for VM to come online...
(default) DBG | Not there yet 1/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 2/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 3/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 4/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 5/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 6/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 7/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 8/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 9/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 10/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 11/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 12/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 13/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 14/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 15/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 16/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 17/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 18/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 19/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 20/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 21/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 22/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 23/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 24/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 25/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 26/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 27/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 28/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 29/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 30/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 31/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 32/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 33/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 34/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 35/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 36/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 37/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 38/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 39/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 40/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 41/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 42/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 43/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 44/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 45/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 46/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 47/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 48/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 49/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 50/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 51/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 52/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 53/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 54/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 55/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 56/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 57/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 58/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 59/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 60/60, error: couldn't find MAC address in VMX file /Users/dominik/.docker/machine/machines/default/default.vmx
Error creating machine: Error in driver during machine creation: Machine didn't return an IP after 120 seconds, aborting
Opting out of crash reporting.
```

**Comment by dtomasi** [comment]
any news on this issue ? thx

**Comment by dtomasi** [comment]
OK, seams that this was fixed in a newer version. 

```
$ docker-machine ls
NAME      ACTIVE   DRIVER         STATE     URL                         SWARM   DOCKER    ERRORS
default   *        vmwarefusion   Running   tcp://172.16.169.128:2376           v1.10.3   
$ docker --version
Docker version 1.10.2, build c3959b1
$ docker-machine --version
docker-machine version 0.6.0, build e27fb87
```

Thank you.

**Comment by JeanMertz** [comment]
I'm having the exact same issue:

```
docker-machine -D create --driver vmwarefusion --vmwarefusion-cpu-count 4 --vmwarefusion-disk-size 30000 --vmwarefusion-memory-size 8192 default
Docker Machine Version:  0.6.0, build e27fb87
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver vmwarefusion
Plugin server listening at address 127.0.0.1:50365
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(flag-lookup) Calling .GetMachineName
(flag-lookup) Calling .DriverName
(flag-lookup) Calling .GetCreateFlags
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver vmwarefusion
Plugin server listening at address 127.0.0.1:50369
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(default) Calling .GetMachineName
(default) Calling .DriverName
(default) Calling .GetCreateFlags
(default) Calling .SetConfigFromFlags
Running pre-create checks...
(default) Calling .PreCreateCheck
(default) DBG | local Boot2Docker ISO version:  v1.10.3
(default) Calling .GetConfigRaw
Creating machine...
(default) Calling .Create
(default) DBG | local Boot2Docker ISO version:  v1.10.3
(default) Copying /Users/Jean/.docker/machine/cache/boot2docker.iso to /Users/Jean/.docker/machine/machines/default/boot2docker.iso...
(default) Creating SSH key...
(default) Creating VM...
(default) Creating disk '/Users/Jean/.docker/machine/machines/default/default.vmdk'
(default) Virtual disk creation successful.
(default) Starting default...
(default) DBG | executing: /Applications/VMware Fusion.app/Contents/Library/vmrun start /Users/Jean/.docker/machine/machines/default/default.vmx nogui
(default) Waiting for VM to come online...
(default) DBG | Not there yet 1/60, error: couldn't find MAC address in VMX file /Users/Jean/.docker/machine/machines/default/default.vmx
(default) DBG | Not there yet 60/60, error: couldn't find MAC address in VMX file /Users/Jean/.docker/machine/machines/default/default.vmx
Error creating machine: Error in driver during machine creation: Machine didn't return an IP after 120 seconds, aborting
open : no such file or directory
notifying bugsnag: [Error creating machine: Error in driver during machine creation: Machine didn't return an IP after 120 seconds, aborting]
```

```
docker-machine --version
docker-machine version 0.6.0, build e27fb87

docker --version
Docker version 1.10.3, build 20f81dd
```

**Comment by JeanMertz** [comment]
Actually, this might be related to not having enough disk space available. I noticed I only had a couple of gigs left, so I cleared some more space, and now things seem to work as expected.

**Comment by frapposelli** [comment]
@JeanMertz good catch!

**Comment by jpca999** [comment]
whats the minimum disk space do we need for it to run ?
I got 44gb of free disk space but i still get the error. 



$ docker-machine  create --driver vmwarefusion --vmwarefusion-cpu-count "4" --vmwarefusion-disk-size "6000" --vmwarefusion-memory-size "8190" docker04


○ docker-machine  create --driver vmwarefusion --vmwarefusion-cpu-count "4" --vmwarefusion-disk-size "6000" --vmwarefusion-memory-size "8190" docker04
Running pre-create checks...
Creating machine...
(docker04) Copying /Users/jay/.docker/machine/cache/boot2docker.iso to /Users/jay/.docker/machine/machines/docker04/boot2docker.iso...
(docker04) Creating SSH key...
(docker04) Creating VM...
(docker04) Creating disk '/Users/jay/.docker/machine/machines/docker04/docker04.vmdk'
(docker04) Virtual disk creation successful.
(docker04) Starting docker04...
(docker04) Waiting for VM to come online...
Error creating machine: Error in driver during machine creation: Machine didn't return an IP after 120 seconds, aborting

**Comment by monoburn** [comment]
Clearing some disk space made it work for me. Thanks!

**Comment by jp-ca** [comment]
I got 22 gig free. How much should I keep aside for this ?
